### ISSUE TITLE
Video is black on Windows Phone 8.1 HTML5 player

### ISSUE THREAD

**Issue by skosonen** [kaltura/mwEmbed#1614]
Video is not displayed on Windows Phone 8.1 (Lumia 920) HTML5 player. Only audio is played.

**Comment by zoharbabin** [comment]
@skosonen can you provide a test URL and the browser and version you're using?

**Comment by skosonen** [comment]
Test URL:
http://oneway.tv/video/0_9mprjpze
Test device: Nokia Lumia 920 
OS: Windows Phone 8.1
Browser: IE11

**Comment by DBezemer** [comment]
7a79e9475f1519958855744bd3a10adf9f60fa1b should fix this, can you test it?

**Comment by heiiko** [comment]
@DBezemer, same issue - we've tested this fix with our Lumia 925 (WP 8.1), but still no image is rendered (you only hear the audio track).

**Comment by coreliogithub** [comment]
We have just tested with our device and the new player 2.32 and this issue is still not fixed, unbelievable! 
device: Nokia Lumia 925, running windows phone 8.1
Test url: http://www.kaltura.com/tiny/jvqi1

**Comment by dazrean** [comment]
I face with the same issue. Have reverted back to version 2.31

**Comment by heiiko** [comment]
Great, with v2.33.rc7 the play button and preview thumbnail are now properly shown on my WP8.1 device.

Loading a DPF preroll on the other hand still seems to break something: the video plays for 2 seconds; then the preroll gets played; the screen then turns black and spinner goes in an infinite loop

**Comment by OrenMe** [comment]
Hi @skosonen  - issue seems resolved per heiiko's comment. 
Closing due to inactivity. please reopen if this is still relevant. Thanks.
